# Generated by Django 4.0.2 on 2022-02-07 05:28

import cryptocurrency.utils
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='id',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='index',
            field=models.IntegerField(default=cryptocurrency.utils.create_new_ref_number, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='timestamp',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
    ]
